<div class="mapCon01"></div>

<div class="map_wrap">
    <div class="sub_title">
        <h1 class="buri">MAPS</h1>
        <p class="poppins">
            Enjoy the scenery in front of your eyes enjoying the morning sun.<br>
            The freshness of the green nature.
        </p>
    </div>
    <script src="/js/jquery.rwdImageMaps.min.js"></script>
    <script>
        $(document).ready(function(){
            $('img[usemap]').rwdImageMaps();
        });
    </script>
    <div class="map">
        <!-- Image Map Generated by http://www.image-map.net/ -->
        <img src="/images/room/roommap.jpg" usemap="#image-map" class="img_00">

        <!-- <map name="image-map">
            <area target="" alt="room A" title="room A" href="/room/1" coords="1741,937,1186,511" shape="rect">
            <area target="" alt="room B" title="room B" href="/room/2" coords="1100,434,620,926" shape="rect">
            <area target="" alt="room C" title="room C" href="/room/3" coords="64,394,572,831" shape="rect">
            <area target="" alt="room D" title="room D" href="/room/4" coords="237,95,940,356" shape="rect">
            <area target="" alt="room VIP" title="room VIP" href="/room/5" coords="1010,71,1722,355" shape="rect">
        </map> -->
    </div>
</div>
