<link rel="stylesheet" href="/css/roompreview.css" type="text/css">
<link rel="stylesheet" href="/css/default.css" type="text/css">
<link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css">
<link rel="stylesheet" href="https://unpkg.com/swiper@8/swiper-bundle.min.css">
<link rel="stylesheet" href="/css/swiper.css" type="text/css">
<meta name="viewport" content="width=device-width, initial-scale=1">
<?php
    include('header.php');
    ?>
<div class="pretitle">

</div>
<div class="guidemap">
   <!-- Image Map Generated by http://www.image-map.net/ -->
<!-- Image Map Generated by http://www.image-map.net/ -->
<img src="/images/preview/guidemap.jpg" usemap="#image-map">

<!-- <map name="image-map">
    <area target="" alt="가온" title="가온" href="http://xn--bj0b46pe4m2hbo4inpq.kr/room01" coords="264,188,34" shape="circle">
    <area target="" alt="가온" title="가온" href="http://xn--bj0b46pe4m2hbo4inpq.kr/room01" coords="236,273,39" shape="circle">
    <area target="" alt="가온" title="가온" href="http://xn--bj0b46pe4m2hbo4inpq.kr/room01" coords="362,315,32" shape="circle">
    <area target="" alt="가온" title="가온" href="http://xn--bj0b46pe4m2hbo4inpq.kr/room01" coords="459,325,39" shape="circle">
    <area target="" alt="가온" title="가온" href="http://xn--bj0b46pe4m2hbo4inpq.kr/room01" coords="558,289,38" shape="circle">
    <area target="" alt="가온" title="가온" href="http://xn--bj0b46pe4m2hbo4inpq.kr/room01" coords="474,637,40" shape="circle">
    <area target="" alt="가온" title="가온" href="http://xn--bj0b46pe4m2hbo4inpq.kr/room01" coords="575,605,36" shape="circle">
    <area target="" alt="가온" title="가온" href="http://xn--bj0b46pe4m2hbo4inpq.kr/room01" coords="668,567,33" shape="circle">
    <area target="" alt="가온" title="가온" href="http://xn--bj0b46pe4m2hbo4inpq.kr/room01" coords="763,525,38" shape="circle">
    <area target="" alt="가온" title="가온" href="http://xn--bj0b46pe4m2hbo4inpq.kr/room01" coords="855,479,32" shape="circle">
    <area target="" alt="가온" title="가온" href="http://xn--bj0b46pe4m2hbo4inpq.kr/room01" coords="949,442,32" shape="circle">
    <area target="" alt="가온" title="가온" href="http://xn--bj0b46pe4m2hbo4inpq.kr/room01" coords="1039,402,35" shape="circle">
    <area target="" alt="다온" title="다온" href="http://xn--bj0b46pe4m2hbo4inpq.kr/room02" coords="1151,326,37" shape="circle">
    <area target="" alt="다온" title="다온" href="http://xn--bj0b46pe4m2hbo4inpq.kr/room02" coords="1039,211,40" shape="circle">
    <area target="" alt="다온" title="다온" href="http://xn--bj0b46pe4m2hbo4inpq.kr/room02" coords="886,270,43" shape="circle">
    <area target="" alt="다온" title="다온" href="http://xn--bj0b46pe4m2hbo4inpq.kr/room02" coords="962,132,38" shape="circle">
    <area target="" alt="라온" title="라온" href="http://xn--bj0b46pe4m2hbo4inpq.kr/room03" coords="770,134,45" shape="circle">
    <area target="" alt="라온" title="라온" href="http://xn--bj0b46pe4m2hbo4inpq.kr/room03" coords="626,114,43" shape="circle">
    <area target="" alt="라온" title="라온" href="http://xn--bj0b46pe4m2hbo4inpq.kr/room03" coords="484,147,42" shape="circle">
    <area target="" alt="라온디럭스" title="라온디럭스" href="http://xn--bj0b46pe4m2hbo4inpq.kr/room04" coords="71,137,48" shape="circle">
</map> -->
<div class="map_btn">
    <a href="http://xn--bj0b46pe4m2hbo4inpq.kr/room01">잎새</a>
    <a href="http://xn--bj0b46pe4m2hbo4inpq.kr/room03">수풀</a>
    <a href="http://xn--bj0b46pe4m2hbo4inpq.kr/room04">온빛</a>
</div>
</div>
<!-- <div class="previewslide">
    <div class="swiper-wrap">
        <div class="swiper12">
            <div class="swiper-wrapper">
                <div class="swiper-slide">
                    <img src="/images/preview/01_01.jpg" alt="">
                </div>
                <div class="swiper-slide">
                    <img src="/images/preview/01_02.jpg" alt="">
                </div>
                <div class="swiper-slide">
                    <img src="/images/preview/01_03.jpg" alt="">
                </div>
                <div class="swiper-slide">
                    <img src="/images/preview/01_04.jpg" alt="">
                </div>
                <div class="swiper-slide">
                    <img src="/images/preview/01_05.jpg" alt="">
                </div>
                <div class="swiper-slide">
                    <img src="/images/preview/01_06.jpg" alt="">
                </div>
                <div class="swiper-slide">
                    <img src="/images/preview/01_07.jpg" alt="">
                </div>
                     <div class="swiper-slide">
                    <img src="/images/preview/01_08.jpg" alt="">
                </div>
            </div>
            <div class="swiper-button-prev prebtn1"></div>
		<div class="swiper-button-next prebtn2"></div>
        </div>
      
    </div>
</div> -->



<!-- <div class="previewslide-m">
    <div class="swiper-wrap">
        <div class="swiper">
            <div class="swiper-wrapper">
                <div class="swiper-slide">
                    <img src="/images/preview/m/01_01.jpg" alt="">
                </div>
                <div class="swiper-slide">
                    <img src="/images/preview/m/01_02.jpg" alt="">
                </div>
                <div class="swiper-slide">
                    <img src="/images/preview/m/01_03.jpg" alt="">
                </div>
                <div class="swiper-slide">
                    <img src="/images/preview/m/01_04.jpg" alt="">
                </div>
                <div class="swiper-slide">
                    <img src="/images/preview/m/01_05.jpg" alt="">
                </div>
                <div class="swiper-slide">
                    <img src="/images/preview/m/01_06.jpg" alt="">
                </div>
                <div class="swiper-slide">
                    <img src="/images/preview/m/01_07.jpg" alt="">
                </div>
                <div class="swiper-slide">
                    <img src="/images/preview/m/01_08.jpg" alt="">
                </div>
            </div>
            <div class="swiper-button-prev prebtn1"></div>
		<div class="swiper-button-next prebtn2"></div>
        </div>
    </div>
</div> -->
<div class="pretitle">
<h1>PREVIEW</h1>
<p>참!좋은 글램핑은 여러분에게 편안한 휴식과 행복한 추억을 선물해드리기 위해서 다양한 객실을 준비했습니다.<br>
취향과 분위기에 맞춰 객실을 골라보세요~!
</p>
</div>
<div class="previewlist">
    <?php
    include('roompre.php');
    ?>
</div> 

<script src='http://code.jquery.com/jquery-1.9.1.min.js'></script>
<script src="/js/main.js"></script>
<script src="https://unpkg.com/swiper@8/swiper-bundle.min.js"></script>
<div class="underbox">
        <div class="bg11">
            <img src="/images/main/bg11.png" alt="">
        </div>
        <div class="underline">
        </div>
    </div>
<?php
include('footer.php');
?>